/*
 * Java code generated by beanGenerator.py
 * 02.19.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * The friendship class for describing who is connected to who.
 */
package com.hola.serverSide.ariApplication.db.beans;
/*
 * Import statements 
 */
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AccountFriend
{
	private String usernameOrEmail; // The username or email that is used to login to the Hola! system.
	private String friend; // The username or email of the friend that he/she uses to login to the Hola! system.
	private static final ObjectMapper objectMapper = new ObjectMapper ();



	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public AccountFriend ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public AccountFriend (String _usernameOrEmail, String _friend)
	{
		this.usernameOrEmail = _usernameOrEmail;
		this.friend          = _friend;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("usernameOrEmail")
	public void setUsernameOrEmail (String _usernameOrEmail)
	{
		this.usernameOrEmail = _usernameOrEmail;
	}


	@JsonProperty ("friend")
	public void setFriend (String _friend)
	{
		this.friend = _friend;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("usernameOrEmail")
	public String getUsernameOrEmail ()
	{
		return this.usernameOrEmail;
	}


	@JsonProperty ("friend")
	public String getFriend ()
	{
		return this.friend;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "usernameOrEmail: " + usernameOrEmail+ " " + "friend: " + friend;
	}
	/*
	 * get JSON string object
	 */
	public String toJsonString ()
	{
		String thisBeanAsJson = null;
		try
		{
			thisBeanAsJson = objectMapper.writeValueAsString (this);
		}
		catch (JsonProcessingException e)
		{
			e.printStackTrace ();
		}
		finally
		{
			return thisBeanAsJson;
		}
	}
}
