/*
 * Java code generated by beanGenerator.py
 * 02.19.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A class for describing policies for an Hola account.
 */
package com.hola.serverSide.ariApplication.db.beans;
/*
 * Import statements 
 */
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AccountPolicy
{
	private String usernameOrEmail; // The username or email that is used to login to the Hola! system.
	private int    extension; // The integer extension number that the user is assigned to.
	private String policies; // The JSON string of the policies for this Hola! account.
	private static final ObjectMapper objectMapper = new ObjectMapper ();



	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public AccountPolicy ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public AccountPolicy (String _usernameOrEmail, int _extension, String _policies)
	{
		this.usernameOrEmail = _usernameOrEmail;
		this.extension       = _extension;
		this.policies        = _policies;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("usernameOrEmail")
	public void setUsernameOrEmail (String _usernameOrEmail)
	{
		this.usernameOrEmail = _usernameOrEmail;
	}


	@JsonProperty ("extension")
	public void setExtension (int _extension)
	{
		this.extension = _extension;
	}


	@JsonProperty ("policies")
	public void setPolicies (String _policies)
	{
		this.policies = _policies;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("usernameOrEmail")
	public String getUsernameOrEmail ()
	{
		return this.usernameOrEmail;
	}


	@JsonProperty ("extension")
	public int getExtension ()
	{
		return this.extension;
	}


	@JsonProperty ("policies")
	public String getPolicies ()
	{
		return this.policies;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "usernameOrEmail: " + usernameOrEmail+ " " + "extension: " + extension+ " " + "policies: " + policies;
	}
	/*
	 * get JSON string object
	 */
	public String toJsonString ()
	{
		String thisBeanAsJson = null;
		try
		{
			thisBeanAsJson = objectMapper.writeValueAsString (this);
		}
		catch (JsonProcessingException e)
		{
			e.printStackTrace ();
		}
		finally
		{
			return thisBeanAsJson;
		}
	}
}
