/*
 * Java code autogenerated by enumGenerator.py
 * 12.29.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * HSMEvent
 */
package com.hola.serverSide.appInterface.hsm;

/*
 * Import statements 
 */
public enum HSMEvent
{
    ReceivedAuthRequest              (1), // An auth request has been received.
    ReceivedInfoRequest              (2), // An Info request has been received.
    ReceivedContactAddRequest        (3), // A Contact add request has been received.
    FailedAuthRequest                (4), // The auth request failed for authentication.
    SendReachabilityUpdate           (5), // The app should be sent a rechability update for a specific user (internal trigger).
    ReceivedStatusUpdate             (6), // A status update was received from the app.
    ReceivedReachabilityRequest      (7), // A rechability request was received from the app.
    ReceivedCurrentCallRequest       (8), // A current call request was received from the app.
    Success                          (9), // A generic success event.
    Error                           (10), // A generic error event.

    /*
     * Other, not so obvious events
     */
    SendAuthResponse                (21),
    
    SendStatusUpdateResponse        (31),

    SendReachabilityRequestResponse (41),

    ReceivedReachabilityUpdate      (51),
    
    ReceivedGoingToBackground       (61),
    ReceivedGoingToForeground       (62),

    CleanUp                         (81),
    
    UNKNOWN                         (99);

    private final int eventTypeInt;


    HSMEvent (int _eventTypeInt)
    {
	this.eventTypeInt = _eventTypeInt;
    }

    public int getEventTypeInt ()
    {
	return this.eventTypeInt;
    }

    public String getTypeString ()
    {
	switch (this)
	    {
	    case ReceivedAuthRequest:
		{
		    return "ReceivedAuthRequest";
		}
	    case ReceivedInfoRequest:
		{
		    return "ReceivedInfoRequest";
		}
	    case ReceivedContactAddRequest:
		{
		    return "ReceivedContactAddRequest";
		}
	    case SendAuthResponse:
		{
		    return "SendAuthResponse";
		}
	    case FailedAuthRequest:
		{
		    return "FailedAuthRequest";
		}
	    case SendReachabilityUpdate:
		{
		    return "SendReachabilityUpdate";
		}
	    case ReceivedStatusUpdate:
		{
		    return "ReceivedStatusUpdate";
		}
	    case SendStatusUpdateResponse:
		{
		    return "SendStatusUpdateResponse";
		}
	    case ReceivedReachabilityRequest:
		{
		    return "ReceivedReachabilityRequest";
		}
	    case ReceivedReachabilityUpdate:
		{
		    return "ReceivedReachabilityUpdate";
		}
	    case ReceivedGoingToBackground:
		{
		    return "ReceivedGoingToBackground";
		}
	    case ReceivedGoingToForeground:
		{
		    return "ReceivedGoingToForeground";
		}
	    case ReceivedCurrentCallRequest:
		{
		    return "ReceivedCurrentCallRequest";
		}
	    case CleanUp:
		{
		    return "CleanUp";
		}
	    case Success:
		{
		    return "Success";
		}
	    case Error:
		{
		    return "Error";
		}
	    default:
		return "UNKNOWN HSMEvent TYPE";
	    }
    }
}
