/*
 * Java code autogenerated by enumGenerator.py
 * 12.29.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * HSMState
 */
package com.hola.serverSide.appInterface.hsm;

/*
 * Import statements 
 */

public enum HSMState
{
    Idle                                 (1), // The idle state.
    //WaitForAuth                          (2), // The state where authentication is perfomed for an app.
    //WaitForInfoRequestProcessing         (3), // Info request processing
    ActiveHAPPI                          (4), // The state where connectivity with the app has been established, and the HAPPI server is waiting for other APPI events.
    //WaitForContactAddRequestProcessing   (5), // The state where a contact add request is processed.
    //WaitForReachabilityUpdateResponse    (6), // The state where the server has sent a reachability update to the app, and is waiting for the app to send a response (ack).
    //WaitForReachabilityRequestProcessing (7), // The state where the server has received a reachability request and is processing the information.
    //WaitForStatusUpdateProcessing        (8), // The state where the server has received a status update and is processing the information.
    //WaitForCurrentCallRequestProcessing  (9), // The state where the current call information request is processed.
    WaitForWakeUp                       (10), // The state that the SM is in when the app has gone to the background
    CleanUp                             (11), // The state where clean up happens.
    Error                               (10), // Error state that is used to do miscellaneous state maintenance before going to back to idle state.

    UNKNOWN                             (99);

    private final int stateTypeInt;


    HSMState (int _stateTypeInt)
    {
	this.stateTypeInt = _stateTypeInt;
    }

    public int getStateTypeInt ()
    {
	return this.stateTypeInt;
    }

    public String getStateString ()
    {
	switch (this)
	    {
	    case Idle:
		{
		    return "Idle";
		}
	    // case WaitForAuth:
	    // 	{
	    // 	    return "WaitForAuth";
	    // 	}
	    // case WaitForInfoRequestProcessing:
	    // 	{
	    // 	    return "WaitForInfoRequestProcessing";
	    // 	}
	    case ActiveHAPPI:
		{
		    return "ActiveHAPPI";
		}
	    // case WaitForReachabilityUpdateResponse:
	    // 	{
	    // 	    return "WaitForReachabilityUpdateResponse";
	    // 	}
	    // case WaitForReachabilityRequestProcessing:
	    // 	{
	    // 	    return "WaitForReachabilityRequestProcessing";
	    // 	}
	    // case WaitForStatusUpdateProcessing:
	    // 	{
	    // 	    return "WaitForStatusUpdateProcessing";
	    // 	}
	    // case WaitForContactAddRequestProcessing:
	    // 	{
	    // 	    return "WaitForContactAddRequestProcessing";
	    // 	}
	    // case WaitForCurrentCallRequestProcessing:
	    // 	{
	    // 	    return "WaitForCurrentCallRequestProcessing";
	    // 	}
	    case WaitForWakeUp:
		{
		    return "WaitForWakeUp";
		}
	    case CleanUp:
		{
		    return "CleanUp";
		}
	    case Error:
		{
		    return "ERROR";
		}
	    default:
		return "UNKNOWN HSMState TYPE";
	    }
    }
}
