/*
 * Java code generated by beanGenerator.py
 * 02.19.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A class for describing an Hola account.
 */
package com.hola.serverSide.appInterface.db.beans;
/*
 * Import statements 
 */
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.annotation.JsonProperty;

public class HolaAccount
{
	private String usernameOrEmail; // The username or email that is used to login to the Hola! system.
	private int    extension; // The integer extension number that the user is assigned to.
	private String firstname; // The first name of the user.
	private String lastname; // The last name of the user.
	private static final ObjectMapper objectMapper = new ObjectMapper ();



	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public HolaAccount ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public HolaAccount (String _usernameOrEmail, int _extension, String _firstname, String _lastname)
	{
		this.usernameOrEmail = _usernameOrEmail;
		this.extension       = _extension;
		this.firstname       = _firstname;
		this.lastname        = _lastname;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("usernameOrEmail")
	public void setUsernameOrEmail (String _usernameOrEmail)
	{
		this.usernameOrEmail = _usernameOrEmail;
	}


	@JsonProperty ("extension")
	public void setExtension (int _extension)
	{
		this.extension = _extension;
	}


	@JsonProperty ("firstname")
	public void setFirstname (String _firstname)
	{
		this.firstname = _firstname;
	}


	@JsonProperty ("lastname")
	public void setLastname (String _lastname)
	{
		this.lastname = _lastname;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("usernameOrEmail")
	public String getUsernameOrEmail ()
	{
		return this.usernameOrEmail;
	}


	@JsonProperty ("extension")
	public int getExtension ()
	{
		return this.extension;
	}


	@JsonProperty ("firstname")
	public String getFirstname ()
	{
		return this.firstname;
	}


	@JsonProperty ("lastname")
	public String getLastname ()
	{
		return this.lastname;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "usernameOrEmail: " + usernameOrEmail+ " " + "extension: " + extension+ " " + "firstname: " + firstname+ " " + "lastname: " + lastname;
	}
	/*
	 * get JSON string object
	 */
	public String toJsonString ()
	{
		String thisBeanAsJson = null;
		try
		{
			thisBeanAsJson = objectMapper.writeValueAsString (this);
		}
		catch (JsonProcessingException e)
		{
			e.printStackTrace ();
		}
		finally
		{
			return thisBeanAsJson;
		}
	}
}
