/*
 * Java code autogenerated by beanGenerator.py
 * 12.12.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * An action plan that will be used to scope out the full action plan for a incoming call. This forms the full list of plan-A, plan-B, plan-C action items for a call. In other words, Hola! will try to execute plan-A first, and then plan-B (if plan-A fails), etc.
 */
package com.hola.serverSide.appInterface.policy;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class ActionPlan
{
    private List<ActionGroup> actionGroups; // A collection of action groups that will be executed in one action group at a time.
    private int index; // index of what action group in the action plan Hola! is currently executing

    /*
     * Constructors
     * Empty/default (see 
     *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
     * full, and partial (for derived classes)
     *
     */
    public ActionPlan ()
    {
	// For Jackson ObjectMapper's sanity!
	this.index = 0;
	this.actionGroups = new ArrayList<ActionGroup> ();
    }
    public ActionPlan (List<ActionGroup> _actionGroups)
    {
	this.actionGroups    = _actionGroups;
	this.index = 0;
    }
    /*
     * Setters
     */
    public void setActionGroups (List<ActionGroup> _actionGroups)
    {
	this.actionGroups = _actionGroups;
    }

    public void addActionGroup (ActionGroup _actionGroup)
    {
        this.actionGroups.add (_actionGroup);
    }

    public void incIndex ()
    {
	this.index ++;
    }
    /*
     * Getters
     */
    public List<ActionGroup> getActionGroups ()
    {
	return this.actionGroups;
    }


    public int getIndex ()
    {
	return this.index;
    }
    /*
     * Overide of toString() to help debug, log etc.
     */
    @Override
    public String toString ()
    {

	String list0Str="[";
	for (ActionGroup var: this.actionGroups) 
	    {
		list0Str += var.toString () + ", ";
	    }
	list0Str += "]";
	return "actionGroups: " + list0Str + ", actionPlanIndex = " + this.index;
    }
}
