/*
 * Java code autogenerated by beanGenerator.py
 * 12.12.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A collection of actions, grouped for a particular policy.
 */
package com.hola.serverSide.appInterface.policy;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class ActionGroup
{
    private List<Action> actions; // The collection of actions.


    /*
     * Constructors
     * Empty/default (see 
     *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
     * full, and partial (for derived classes)
     *
     */
    public ActionGroup ()
    {
	// For Jackson ObjectMapper's sanity!
	this.actions = new ArrayList <Action> ();
    }
    public ActionGroup (List<Action> _actions)
    {
	this.actions = _actions;
    }
    /*
     * Setters
     */
    public void setActions (List<Action> _actions)
    {
	this.actions = _actions;
    }


    public void add (Action _action)
    {
	this.actions.add (_action);
    }

    /*
     * Getters
     */
    public List<Action> getActions ()
    {
	return this.actions;
    }


    /*
     * Overide of toString() to help debug, log etc.
     */
    @Override
    public String toString ()
    {

	String list0Str="[";
	for (Action var: actions) 
	    {
		list0Str += var.toString () + ", ";
	    }
	list0Str += "]";
	return "actions: " + list0Str;
    }
}
