/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Details of a Stasis application
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class Application
{
	private List<String> bridge_ids; // Id's for bridges subscribed to.
	private List<String> channel_ids; // Id's for channels subscribed to.
	private List<String> device_names; // Names of the devices subscribed to.
	private List<String> endpoint_ids; // {tech}/{resource} for endpoints subscribed to.
	private String       name; // Name of this application


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Application ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Application (List<String> _bridge_ids, List<String> _channel_ids, List<String> _device_names, List<String> _endpoint_ids, String _name)
	{
		this.bridge_ids   = _bridge_ids;
		this.channel_ids  = _channel_ids;
		this.device_names = _device_names;
		this.endpoint_ids = _endpoint_ids;
		this.name         = _name;
	}
	/*
	 * Setters
	 */
	public void setBridge_ids (List<String> _bridge_ids)
	{
		this.bridge_ids = _bridge_ids;
	}


	public void setChannel_ids (List<String> _channel_ids)
	{
		this.channel_ids = _channel_ids;
	}


	public void setDevice_names (List<String> _device_names)
	{
		this.device_names = _device_names;
	}


	public void setEndpoint_ids (List<String> _endpoint_ids)
	{
		this.endpoint_ids = _endpoint_ids;
	}


	public void setName (String _name)
	{
		this.name = _name;
	}


	/*
	 * Getters
	 */
	public List<String> getBridge_ids ()
	{
		return this.bridge_ids;
	}


	public List<String> getChannel_ids ()
	{
		return this.channel_ids;
	}


	public List<String> getDevice_names ()
	{
		return this.device_names;
	}


	public List<String> getEndpoint_ids ()
	{
		return this.endpoint_ids;
	}


	public String getName ()
	{
		return this.name;
	}


}
