/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Asterisk system information
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class AsteriskInfo
{
	private BuildInfo  build; // (optional) Info about how Asterisk was built
	private ConfigInfo config; // (optional) Info about Asterisk configuration
	private StatusInfo status; // (optional) Info about Asterisk status
	private SystemInfo system; // (optional) Info about the system running Asterisk


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public AsteriskInfo ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public AsteriskInfo (BuildInfo _build, ConfigInfo _config, StatusInfo _status, SystemInfo _system)
	{
		this.build  = _build;
		this.config = _config;
		this.status = _status;
		this.system = _system;
	}
	/*
	 * Setters
	 */
	public void setBuild (BuildInfo _build)
	{
		this.build = _build;
	}


	public void setConfig (ConfigInfo _config)
	{
		this.config = _config;
	}


	public void setStatus (StatusInfo _status)
	{
		this.status = _status;
	}


	public void setSystem (SystemInfo _system)
	{
		this.system = _system;
	}


	/*
	 * Getters
	 */
	public BuildInfo getBuild ()
	{
		return this.build;
	}


	public ConfigInfo getConfig ()
	{
		return this.config;
	}


	public StatusInfo getStatus ()
	{
		return this.status;
	}


	public SystemInfo getSystem ()
	{
		return this.system;
	}


}
