/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Notification that an attended transfer has occurred.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class BridgeAttendedTransfer extends Event
{
	private String    destination_application; // (optional) Application that has been transferred into
	private String    destination_bridge; // (optional) Bridge that survived the merge result
	private Channel   destination_link_first_leg; // (optional) First leg of a link transfer result
	private Channel   destination_link_second_leg; // (optional) Second leg of a link transfer result
	private Bridge    destination_threeway_bridge; // (optional) Bridge that survived the threeway result
	private Channel   destination_threeway_channel; // (optional) Transferer channel that survived the threeway result
	private String    destination_type; // How the transfer was accomplished
	private boolean   is_external; // Whether the transfer was externally initiated or not
	private Channel   replace_channel; // (optional) The channel that is replacing transferer_first_leg in the swap
	private String    result; // The result of the transfer attempt
	private Channel   transfer_target; // (optional) The channel that is being transferred to
	private Channel   transferee; // (optional) The channel that is being transferred
	private Channel   transferer_first_leg; // First leg of the transferer
	private Bridge    transferer_first_leg_bridge; // (optional) Bridge the transferer first leg is in
	private Channel   transferer_second_leg; // Second leg of the transferer
	private Bridge    transferer_second_leg_bridge; // (optional) Bridge the transferer second leg is in


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public BridgeAttendedTransfer ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public BridgeAttendedTransfer (String _type, String _application, Timestamp _timestamp, String _destination_application, String _destination_bridge, Channel _destination_link_first_leg, Channel _destination_link_second_leg, Bridge _destination_threeway_bridge, Channel _destination_threeway_channel, String _destination_type, boolean _is_external, Channel _replace_channel, String _result, Channel _transfer_target, Channel _transferee, Channel _transferer_first_leg, Bridge _transferer_first_leg_bridge, Channel _transferer_second_leg, Bridge _transferer_second_leg_bridge)
	{
		super (_type, _application, _timestamp);
		this.destination_application      = _destination_application;
		this.destination_bridge           = _destination_bridge;
		this.destination_link_first_leg   = _destination_link_first_leg;
		this.destination_link_second_leg  = _destination_link_second_leg;
		this.destination_threeway_bridge  = _destination_threeway_bridge;
		this.destination_threeway_channel = _destination_threeway_channel;
		this.destination_type             = _destination_type;
		this.is_external                  = _is_external;
		this.replace_channel              = _replace_channel;
		this.result                       = _result;
		this.transfer_target              = _transfer_target;
		this.transferee                   = _transferee;
		this.transferer_first_leg         = _transferer_first_leg;
		this.transferer_first_leg_bridge  = _transferer_first_leg_bridge;
		this.transferer_second_leg        = _transferer_second_leg;
		this.transferer_second_leg_bridge = _transferer_second_leg_bridge;
	}
	/*
	 * Setters
	 */
	public void setDestination_application (String _destination_application)
	{
		this.destination_application = _destination_application;
	}


	public void setDestination_bridge (String _destination_bridge)
	{
		this.destination_bridge = _destination_bridge;
	}


	public void setDestination_link_first_leg (Channel _destination_link_first_leg)
	{
		this.destination_link_first_leg = _destination_link_first_leg;
	}


	public void setDestination_link_second_leg (Channel _destination_link_second_leg)
	{
		this.destination_link_second_leg = _destination_link_second_leg;
	}


	public void setDestination_threeway_bridge (Bridge _destination_threeway_bridge)
	{
		this.destination_threeway_bridge = _destination_threeway_bridge;
	}


	public void setDestination_threeway_channel (Channel _destination_threeway_channel)
	{
		this.destination_threeway_channel = _destination_threeway_channel;
	}


	public void setDestination_type (String _destination_type)
	{
		this.destination_type = _destination_type;
	}


	public void setIs_external (boolean _is_external)
	{
		this.is_external = _is_external;
	}


	public void setReplace_channel (Channel _replace_channel)
	{
		this.replace_channel = _replace_channel;
	}


	public void setResult (String _result)
	{
		this.result = _result;
	}


	public void setTransfer_target (Channel _transfer_target)
	{
		this.transfer_target = _transfer_target;
	}


	public void setTransferee (Channel _transferee)
	{
		this.transferee = _transferee;
	}


	public void setTransferer_first_leg (Channel _transferer_first_leg)
	{
		this.transferer_first_leg = _transferer_first_leg;
	}


	public void setTransferer_first_leg_bridge (Bridge _transferer_first_leg_bridge)
	{
		this.transferer_first_leg_bridge = _transferer_first_leg_bridge;
	}


	public void setTransferer_second_leg (Channel _transferer_second_leg)
	{
		this.transferer_second_leg = _transferer_second_leg;
	}


	public void setTransferer_second_leg_bridge (Bridge _transferer_second_leg_bridge)
	{
		this.transferer_second_leg_bridge = _transferer_second_leg_bridge;
	}


	/*
	 * Getters
	 */
	public String getDestination_application ()
	{
		return this.destination_application;
	}


	public String getDestination_bridge ()
	{
		return this.destination_bridge;
	}


	public Channel getDestination_link_first_leg ()
	{
		return this.destination_link_first_leg;
	}


	public Channel getDestination_link_second_leg ()
	{
		return this.destination_link_second_leg;
	}


	public Bridge getDestination_threeway_bridge ()
	{
		return this.destination_threeway_bridge;
	}


	public Channel getDestination_threeway_channel ()
	{
		return this.destination_threeway_channel;
	}


	public String getDestination_type ()
	{
		return this.destination_type;
	}


	public boolean getIs_external ()
	{
		return this.is_external;
	}


	public Channel getReplace_channel ()
	{
		return this.replace_channel;
	}


	public String getResult ()
	{
		return this.result;
	}


	public Channel getTransfer_target ()
	{
		return this.transfer_target;
	}


	public Channel getTransferee ()
	{
		return this.transferee;
	}


	public Channel getTransferer_first_leg ()
	{
		return this.transferer_first_leg;
	}


	public Bridge getTransferer_first_leg_bridge ()
	{
		return this.transferer_first_leg_bridge;
	}


	public Channel getTransferer_second_leg ()
	{
		return this.transferer_second_leg;
	}


	public Bridge getTransferer_second_leg_bridge ()
	{
		return this.transferer_second_leg_bridge;
	}


}
