/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 *  The merging of media from one or more channels. Everyone on the bridge receives the same audio.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class Bridge
{
	private String       bridge_class; // Bridging class
	private String       bridge_type; // Type of bridge technology
	private List<String> channels; // Ids of channels participating in this bridge
	private String       creator; // Entity that created the bridge
	private String       id; // Unique identifier for this bridge
	private String       name; // Name the creator gave the bridge
	private String       technology; // Name of the current bridging technology


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Bridge ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Bridge (String _bridge_class, String _bridge_type, List<String> _channels, String _creator, String _id, String _name, String _technology)
	{
		this.bridge_class = _bridge_class;
		this.bridge_type  = _bridge_type;
		this.channels     = _channels;
		this.creator      = _creator;
		this.id           = _id;
		this.name         = _name;
		this.technology   = _technology;
	}
	/*
	 * Setters
	 */
	public void setBridge_class (String _bridge_class)
	{
		this.bridge_class = _bridge_class;
	}


	public void setBridge_type (String _bridge_type)
	{
		this.bridge_type = _bridge_type;
	}


	public void setChannels (List<String> _channels)
	{
		this.channels = _channels;
	}


	public void setCreator (String _creator)
	{
		this.creator = _creator;
	}


	public void setId (String _id)
	{
		this.id = _id;
	}


	public void setName (String _name)
	{
		this.name = _name;
	}


	public void setTechnology (String _technology)
	{
		this.technology = _technology;
	}


	/*
	 * Getters
	 */
	public String getBridge_class ()
	{
		return this.bridge_class;
	}


	public String getBridge_type ()
	{
		return this.bridge_type;
	}


	public List<String> getChannels ()
	{
		return this.channels;
	}


	public String getCreator ()
	{
		return this.creator;
	}


	public String getId ()
	{
		return this.id;
	}


	public String getName ()
	{
		return this.name;
	}


	public String getTechnology ()
	{
		return this.technology;
	}


}
