/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Notification that one bridge has merged into another.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class BridgeMerged extends Event
{
	private Bridge    bridge; // Bridge that now exists
	private Bridge    bridge_from; // Bridge that was merged into the bridge (see above)


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public BridgeMerged ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public BridgeMerged (String _type, String _application, Timestamp _timestamp, Bridge _bridge, Bridge _bridge_from)
	{
		super (_type, _application, _timestamp);
		this.bridge      = _bridge;
		this.bridge_from = _bridge_from;
	}
	/*
	 * Setters
	 */
	public void setBridge (Bridge _bridge)
	{
		this.bridge = _bridge;
	}


	public void setBridge_from (Bridge _bridge_from)
	{
		this.bridge_from = _bridge_from;
	}


	/*
	 * Getters
	 */
	public Bridge getBridge ()
	{
		return this.bridge;
	}


	public Bridge getBridge_from ()
	{
		return this.bridge_from;
	}


}
