/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Info about how Asterisk was built
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class BuildInfo
{
	private String date; // Date and time when Asterisk was built.
	private String kernel; // Kernel version Asterisk was built on.
	private String machine; // Machine architecture (x86_64, i686, ppc, etc.)
	private String options; // Compile time options, or empty String if default.
	private String os; // OS Asterisk was built on.
	private String user; // Username that build Asterisk


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public BuildInfo ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public BuildInfo (String _date, String _kernel, String _machine, String _options, String _os, String _user)
	{
		this.date    = _date;
		this.kernel  = _kernel;
		this.machine = _machine;
		this.options = _options;
		this.os      = _os;
		this.user    = _user;
	}
	/*
	 * Setters
	 */
	public void setDate (String _date)
	{
		this.date = _date;
	}


	public void setKernel (String _kernel)
	{
		this.kernel = _kernel;
	}


	public void setMachine (String _machine)
	{
		this.machine = _machine;
	}


	public void setOptions (String _options)
	{
		this.options = _options;
	}


	public void setOs (String _os)
	{
		this.os = _os;
	}


	public void setUser (String _user)
	{
		this.user = _user;
	}


	/*
	 * Getters
	 */
	public String getDate ()
	{
		return this.date;
	}


	public String getKernel ()
	{
		return this.kernel;
	}


	public String getMachine ()
	{
		return this.machine;
	}


	public String getOptions ()
	{
		return this.options;
	}


	public String getOs ()
	{
		return this.os;
	}


	public String getUser ()
	{
		return this.user;
	}


}
