/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Caller identification
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class CallerID
{
	private String name; // Name of caller
	private String number; // Number of caller


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public CallerID ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public CallerID (String _name, String _number)
	{
		this.name   = _name;
		this.number = _number;
	}
	/*
	 * Setters
	 */
	public void setName (String _name)
	{
		this.name = _name;
	}


	public void setNumber (String _number)
	{
		this.number = _number;
	}


	/*
	 * Getters
	 */
	public String getName ()
	{
		return this.name;
	}


	public String getNumber ()
	{
		return this.number;
	}


}
