/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object)DTMF received on a channel. This event is sent when the DTMF ends. There is no notification about the start of DTMF
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class ChannelDtmfReceived extends Event
{
	private Channel   channel; // The channel on which DTMF was received
	private String    digit; // DTMF digit received (0
	private int       duration_ms; // Number of milliseconds DTMF was received


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ChannelDtmfReceived ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ChannelDtmfReceived (String _type, String _application, Timestamp _timestamp, Channel _channel, String _digit, int _duration_ms)
	{
		super (_type, _application, _timestamp);
		this.channel     = _channel;
		this.digit       = _digit;
		this.duration_ms = _duration_ms;
	}
	/*
	 * Setters
	 */
	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	public void setDigit (String _digit)
	{
		this.digit = _digit;
	}


	public void setDuration_ms (int _duration_ms)
	{
		this.duration_ms = _duration_ms;
	}


	/*
	 * Getters
	 */
	public Channel getChannel ()
	{
		return this.channel;
	}


	public String getDigit ()
	{
		return this.digit;
	}


	public int getDuration_ms ()
	{
		return this.duration_ms;
	}


}
