/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) User-generated event with additional user-defined fields in the object.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class ChannelUserevent extends Event
{
	private Bridge    bridge; // (optional) A bridge that is signaled with the user event.
	private Channel   channel; // (optional) A channel that is signaled with the user event.
	private Endpoint  endpoint; // (optional) A endpoint that is signaled with the user event.
	private String    eventname; // The name of the user event.
	private Object    userevent; // Custom Userevent data


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ChannelUserevent ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ChannelUserevent (String _type, String _application, Timestamp _timestamp, Bridge _bridge, Channel _channel, Endpoint _endpoint, String _eventname, Object _userevent)
	{
		super (_type, _application, _timestamp);
		this.bridge      = _bridge;
		this.channel     = _channel;
		this.endpoint    = _endpoint;
		this.eventname   = _eventname;
		this.userevent   = _userevent;
	}
	/*
	 * Setters
	 */
	public void setBridge (Bridge _bridge)
	{
		this.bridge = _bridge;
	}


	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	public void setEndpoint (Endpoint _endpoint)
	{
		this.endpoint = _endpoint;
	}


	public void setEventname (String _eventname)
	{
		this.eventname = _eventname;
	}


	public void setUserevent (Object _userevent)
	{
		this.userevent = _userevent;
	}


	/*
	 * Getters
	 */
	public Bridge getBridge ()
	{
		return this.bridge;
	}


	public Channel getChannel ()
	{
		return this.channel;
	}


	public Endpoint getEndpoint ()
	{
		return this.endpoint;
	}


	public String getEventname ()
	{
		return this.eventname;
	}


	public Object getUserevent ()
	{
		return this.userevent;
	}


}
