/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Talking is no longer detected on the channel.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class ChannelTalkingFinished extends Event
{
	private Channel   channel; // The channel on which talking completed.
	private int       duration; // The length of time, in milliseconds, that talking was detected on the channel


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ChannelTalkingFinished ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ChannelTalkingFinished (String _type, String _application, Timestamp _timestamp, Channel _channel, int _duration)
	{
		super (_type, _application, _timestamp);
		this.channel     = _channel;
		this.duration    = _duration;
	}
	/*
	 * Setters
	 */
	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	public void setDuration (int _duration)
	{
		this.duration = _duration;
	}


	/*
	 * Getters
	 */
	public Channel getChannel ()
	{
		return this.channel;
	}


	public int getDuration ()
	{
		return this.duration;
	}


}
