/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Channel variable changed.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class ChannelVarset extends Event
{
	private Channel   channel; // (optional) The channel on which the variable was set. If missing, the variable is a global variable.
	private String    value; // The new value of the variable.
	private String    variable; // The variable that changed.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ChannelVarset ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ChannelVarset (String _type, String _application, Timestamp _timestamp, Channel _channel, String _value, String _variable)
	{
		super (_type, _application, _timestamp);
		this.channel     = _channel;
		this.value       = _value;
		this.variable    = _variable;
	}
	/*
	 * Setters
	 */
	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	public void setValue (String _value)
	{
		this.value = _value;
	}


	public void setVariable (String _variable)
	{
		this.variable = _variable;
	}


	/*
	 * Getters
	 */
	public Channel getChannel ()
	{
		return this.channel;
	}


	public String getValue ()
	{
		return this.value;
	}


	public String getVariable ()
	{
		return this.variable;
	}


}
