/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object)Channel changed Caller ID.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class ChannelCallerId extends Event
{
	private int       caller_presentation; // The integer representation of the Caller Presentation value.
	private String    caller_presentation_txt; // The text representation of the Caller Presentation value.
	private Channel   channel; // The channel that changed Caller ID.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ChannelCallerId ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ChannelCallerId (String _type, String _application, Timestamp _timestamp, int _caller_presentation, String _caller_presentation_txt, Channel _channel)
	{
		super (_type, _application, _timestamp);
		this.caller_presentation     = _caller_presentation;
		this.caller_presentation_txt = _caller_presentation_txt;
		this.channel                 = _channel;
	}
	/*
	 * Setters
	 */
	public void setCaller_presentation (int _caller_presentation)
	{
		this.caller_presentation = _caller_presentation;
	}


	public void setCaller_presentation_txt (String _caller_presentation_txt)
	{
		this.caller_presentation_txt = _caller_presentation_txt;
	}


	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	/*
	 * Getters
	 */
	public int getCaller_presentation ()
	{
		return this.caller_presentation;
	}


	public String getCaller_presentation_txt ()
	{
		return this.caller_presentation_txt;
	}


	public Channel getChannel ()
	{
		return this.channel;
	}


}
