/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object)Notification that a channel has been created.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class ChannelCreated extends Event
{
	private Channel   channel; // Channel that was created


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ChannelCreated ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ChannelCreated (String _type, String _application, Timestamp _timestamp, Channel _channel)
	{
		super (_type, _application, _timestamp);
		this.channel     = _channel;
	}
	/*
	 * Setters
	 */
	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	/*
	 * Getters
	 */
	public Channel getChannel ()
	{
		return this.channel;
	}


}
