/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object)Channel changed location in the dialplan.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class ChannelDialplan extends Event
{
	private Channel   channel; // The channel that changed dialplan location.
	private String    dialplan_app; // The application about to be executed.
	private String    dialplan_app_data; // The data to be passed to the application.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ChannelDialplan ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ChannelDialplan (String _type, String _application, Timestamp _timestamp, Channel _channel, String _dialplan_app, String _dialplan_app_data)
	{
		super (_type, _application, _timestamp);
		this.channel           = _channel;
		this.dialplan_app      = _dialplan_app;
		this.dialplan_app_data = _dialplan_app_data;
	}
	/*
	 * Setters
	 */
	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	public void setDialplan_app (String _dialplan_app)
	{
		this.dialplan_app = _dialplan_app;
	}


	public void setDialplan_app_data (String _dialplan_app_data)
	{
		this.dialplan_app_data = _dialplan_app_data;
	}


	/*
	 * Getters
	 */
	public Channel getChannel ()
	{
		return this.channel;
	}


	public String getDialplan_app ()
	{
		return this.dialplan_app;
	}


	public String getDialplan_app_data ()
	{
		return this.dialplan_app_data;
	}


}
