/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Info about Asterisk configuration
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class ConfigInfo
{
	private String default_language; // Default language for media playback.
	private int    max_channels; // (optional) Maximum number of simultaneous channels.
	private double max_load; // (optional) Maximum load avg on system.
	private int    max_open_files; // (optional) Maximum number of open file handles (files, sockets).
	private String name; // Asterisk system name.
	private SetId  setid; // Effective user/group id for running Asterisk.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ConfigInfo ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public ConfigInfo (String _default_language, int _max_channels, double _max_load, int _max_open_files, String _name, SetId _setid)
	{
		this.default_language = _default_language;
		this.max_channels     = _max_channels;
		this.max_load         = _max_load;
		this.max_open_files   = _max_open_files;
		this.name             = _name;
		this.setid            = _setid;
	}
	/*
	 * Setters
	 */
	public void setDefault_language (String _default_language)
	{
		this.default_language = _default_language;
	}


	public void setMax_channels (int _max_channels)
	{
		this.max_channels = _max_channels;
	}


	public void setMax_load (double _max_load)
	{
		this.max_load = _max_load;
	}


	public void setMax_open_files (int _max_open_files)
	{
		this.max_open_files = _max_open_files;
	}


	public void setName (String _name)
	{
		this.name = _name;
	}


	public void setSetid (SetId _setid)
	{
		this.setid = _setid;
	}


	/*
	 * Getters
	 */
	public String getDefault_language ()
	{
		return this.default_language;
	}


	public int getMax_channels ()
	{
		return this.max_channels;
	}


	public double getMax_load ()
	{
		return this.max_load;
	}


	public int getMax_open_files ()
	{
		return this.max_open_files;
	}


	public String getName ()
	{
		return this.name;
	}


	public SetId getSetid ()
	{
		return this.setid;
	}


}
