/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Java code generated by apiGenerator.py
 * 10.17.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * The DeviceStates ARI API. See https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+DeviceStates+REST+API for details.
 */

import com.sun.jersey.api.client.ClientResponse;
/*
 * Logging
*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DeviceStatesARIAPI
{
	// Logging
	private static final Logger log = LoggerFactory.getLogger (DeviceStatesARIAPI.class.getName ());
	/**
	 *
	 * list: List all ARI controlled device states.
	 *
	*/
	public static ClientResponse list ()
	{
		String RESTURLToUse = "/deviceStates";

		ClientResponse httpResponse = HTTPAPIForARI.get (RESTURLToUse);
		if (httpResponse.getStatus () == 200)
		{
			log.debug ("No errors caught in call to /deviceStates");
		}
		return httpResponse;
	}

	/**
	 *
	 * get: Retrieve the current state of a device.
	 *
	 *
	 * Path parameters:
	 * @param deviceName: String: Name of the device
	*/
	public static ClientResponse get (String deviceName)
	{
		String RESTURLToUse = "/deviceStates/{deviceName}";

		// Correct URI using path params
		RESTURLToUse = RESTURLToUse.replace ("{deviceName}", deviceName);
		ClientResponse httpResponse = HTTPAPIForARI.get (RESTURLToUse);
		if (httpResponse.getStatus () == 200)
		{
			log.debug ("No errors caught in call to /deviceStates/{deviceName}");
		}
		return httpResponse;
	}

	/**
	 *
	 * update: Change the state of a device controlled by ARI. (Note:implicitly creates the device state).
	 *
	 *
	 * Query parameters:
	 * @param deviceState:  string: (required) Device state value. Allowed values
	 *
	 * Path parameters:
	 * @param deviceName: String: Name of the device
	 *
	 * Errors caught:
	 * HTTP Error code 404: Device name is missing
	 * HTTP Error code 409: Uncontrolled device specified
	*/
	public static ClientResponse update (String deviceName, String query)
	{
		String RESTURLToUse = "/deviceStates/{deviceName}";

		// Correct URI using path params
		RESTURLToUse = RESTURLToUse.replace ("{deviceName}", deviceName);
		ClientResponse httpResponse = HTTPAPIForARI.put (RESTURLToUse, query);
		if (httpResponse.getStatus () == 404)
		{
			log.error ("Device name is missing");
		}
		if (httpResponse.getStatus () == 409)
		{
			log.error ("Uncontrolled device specified");
		}
		return httpResponse;
	}

	/**
	 *
	 * delete: Destroy a device-state controlled by ARI.
	 *
	 *
	 * Path parameters:
	 * @param deviceName: String: Name of the device
	 *
	 * Errors caught:
	 * HTTP Error code 404: Device name is missing
	 * HTTP Error code 409: Uncontrolled device specified
	*/
	public static ClientResponse delete (String deviceName)
	{
		String RESTURLToUse = "/deviceStates/{deviceName}";

		// Correct URI using path params
		RESTURLToUse = RESTURLToUse.replace ("{deviceName}", deviceName);
		ClientResponse httpResponse = HTTPAPIForARI.delete (RESTURLToUse);
		if (httpResponse.getStatus () == 404)
		{
			log.error ("Device name is missing");
		}
		if (httpResponse.getStatus () == 409)
		{
			log.error ("Uncontrolled device specified");
		}
		return httpResponse;
	}

}
