/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Notification that a device state has changed.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class DeviceStateChanged extends Event
{
	private DeviceState device_state; // Device state object


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public DeviceStateChanged ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public DeviceStateChanged (String _type, String _application, Timestamp _timestamp, DeviceState _device_state)
	{
		super (_type, _application, _timestamp);
		this.device_state = _device_state;
	}
	/*
	 * Setters
	 */
	public void setDevice_state (DeviceState _device_state)
	{
		this.device_state = _device_state;
	}


	/*
	 * Getters
	 */
	public DeviceState getDevice_state ()
	{
		return this.device_state;
	}


}
