/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Dialing state has changed.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class Dial extends Event
{
	private Channel   caller; // (optional) The calling channel.
	private String    dialstatus; // Current status of the dialing attempt to the peer.
	private String    dialString; // (optional) The dial String for calling the peer channel.
	private String    forward; // (optional) Forwarding target requested by the original dialed channel.
	private Channel   forwarded; // (optional) Channel that the caller has been forwarded to.
	private Channel   peer; // The dialed channel.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Dial ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Dial (String _type, String _application, Timestamp _timestamp, Channel _caller, String _dialstatus, String _dialString, String _forward, Channel _forwarded, Channel _peer)
	{
		super (_type, _application, _timestamp);
		this.caller      = _caller;
		this.dialstatus  = _dialstatus;
		this.dialString  = _dialString;
		this.forward     = _forward;
		this.forwarded   = _forwarded;
		this.peer        = _peer;
	}
	/*
	 * Setters
	 */
	public void setCaller (Channel _caller)
	{
		this.caller = _caller;
	}


	public void setDialstatus (String _dialstatus)
	{
		this.dialstatus = _dialstatus;
	}


	public void setDialString (String _dialString)
	{
		this.dialString = _dialString;
	}


	public void setForward (String _forward)
	{
		this.forward = _forward;
	}


	public void setForwarded (Channel _forwarded)
	{
		this.forwarded = _forwarded;
	}


	public void setPeer (Channel _peer)
	{
		this.peer = _peer;
	}


	/*
	 * Getters
	 */
	public Channel getCaller ()
	{
		return this.caller;
	}


	public String getDialstatus ()
	{
		return this.dialstatus;
	}


	public String getDialString ()
	{
		return this.dialString;
	}


	public String getForward ()
	{
		return this.forward;
	}


	public Channel getForwarded ()
	{
		return this.forwarded;
	}


	public Channel getPeer ()
	{
		return this.peer;
	}


}
