/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Dialplan location (context/extension/priority)
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class DialplanCEP
{
	private String context; // Context in the dialplan
	private String exten; // Extension in the dialplan
	private long   priority; // Priority in the dialplan


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public DialplanCEP ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public DialplanCEP (String _context, String _exten, long _priority)
	{
		this.context  = _context;
		this.exten    = _exten;
		this.priority = _priority;
	}
	/*
	 * Setters
	 */
	public void setContext (String _context)
	{
		this.context = _context;
	}


	public void setExten (String _exten)
	{
		this.exten = _exten;
	}


	public void setPriority (long _priority)
	{
		this.priority = _priority;
	}


	/*
	 * Getters
	 */
	public String getContext ()
	{
		return this.context;
	}


	public String getExten ()
	{
		return this.exten;
	}


	public long getPriority ()
	{
		return this.priority;
	}


}
