/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Endpoint state changed.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class EndpointStateChange extends Event
{
	private Endpoint  endpoint; // Endpoint whose state changed


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public EndpointStateChange ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public EndpointStateChange (String _type, String _application, Timestamp _timestamp, Endpoint _endpoint)
	{
		super (_type, _application, _timestamp);
		this.endpoint    = _endpoint;
	}
	/*
	 * Setters
	 */
	public void setEndpoint (Endpoint _endpoint)
	{
		this.endpoint = _endpoint;
	}


	/*
	 * Getters
	 */
	public Endpoint getEndpoint ()
	{
		return this.endpoint;
	}


}
