/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Message object) Base type for asynchronous events from Asterisk.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Event extends Message
{
	private String    application; // Name of the application receiving the event.
	private Timestamp timestamp; // (optional) Time at which this event was created.

    private static final ObjectMapper objectMapper = new ObjectMapper ();
	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Event ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Event (String _type, String _application, Timestamp _timestamp)
	{
		super (_type);
		this.application = _application;
		this.timestamp   = _timestamp;
	}
	/*
	 * Setters
	 */
	public void setApplication (String _application)
	{
		this.application = _application;
	}


	public void setTimestamp (Timestamp _timestamp)
	{
		this.timestamp = _timestamp;
	}


	/*
	 * Getters
	 */
	public String getApplication ()
	{
		return this.application;
	}


	public Timestamp getTimestamp ()
	{
		return this.timestamp;
	}

    public String toJsonString ()
    {

	String thisBeanAsJson = null;
	try
	    {
		thisBeanAsJson = objectMapper.writeValueAsString (this);
	    }
	catch (JsonProcessingException e)
	    {
		e.printStackTrace ();
	    }
	finally
	    {
		return thisBeanAsJson;
	    }
    }
}
