/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Java code generated by apiGenerator.py
 * 10.17.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * The Events ARI API. See https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Events+REST+API for details.
 */

import com.sun.jersey.api.client.ClientResponse;
/*
 * Logging
*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EventsARIAPI
{
	// Logging
	private static final Logger log = LoggerFactory.getLogger (EventsARIAPI.class.getName ());
	/**
	 *
	 * eventWebsocket: WebSocket connection for events.
	 *
	 *
	 * Query parameters:
	 * @param app: String: (required) Applications to subscribe to.
	*/
	public static ClientResponse eventWebsocket (String query)
	{
		String RESTURLToUse = "/events";

		ClientResponse httpResponse = HTTPAPIForARI.get (RESTURLToUse, query);
		if (httpResponse.getStatus () == 200)
		{
			log.debug ("No errors caught in call to /events");
		}
		return httpResponse;
	}

	/**
	 *
	 * userEvent: Generate a user event.
	 *
	 *
	 * Query parameters:
	 * @param application: String: (required) The name of the application that will receive this event
	 * @param source: String: URI for event source (channel
	 *
	 * Body parameters:
	 * @param variables: containers: The "variables" key in the body object holds custom key/value pairs to add to the user event. Ex. { "variables"
	 *
	 * Path parameters:
	 * @param eventName: String: Event name
	 *
	 * Errors caught:
	 * HTTP Error code 404: Application does not exist.
	 * HTTP Error code 422: Event source not found.
	 * HTTP Error code 400: Invalid even tsource URI or userevent data.
	*/
    public static ClientResponse userEvent (String eventName, String query, String body)
	{
		String RESTURLToUse = "/events/user/{eventName}";

		// Correct URI using path params
		RESTURLToUse = RESTURLToUse.replace ("{eventName}", eventName);
		ClientResponse httpResponse = null; //HTTPAPIForARI.post (RESTURLToUse, query);

		if (body.equals (""))
		    {
			httpResponse = HTTPAPIForARI.post (RESTURLToUse, query);
		    }
		else
		    {
			httpResponse = HTTPAPIForARI.post (RESTURLToUse, query, body);
		    }

		if (httpResponse.getStatus () == 404)
		{
			log.error ("Application does not exist.");
		}
		if (httpResponse.getStatus () == 422)
		{
			log.error ("Event source not found.");
		}
		if (httpResponse.getStatus () == 400)
		{
			log.error ("Invalid even tsource URI or userevent data.");
		}
		return httpResponse;
	}

}
