/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Identifies the format and language of a sound file
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class FormatLangPair
{
	private String format; // Format of recording
	private String language; // Language of recording


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public FormatLangPair ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public FormatLangPair (String _format, String _language)
	{
		this.format   = _format;
		this.language = _language;
	}
	/*
	 * Setters
	 */
	public void setFormat (String _format)
	{
		this.format = _format;
	}


	public void setLanguage (String _language)
	{
		this.language = _language;
	}


	/*
	 * Getters
	 */
	public String getFormat ()
	{
		return this.format;
	}


	public String getLanguage ()
	{
		return this.language;
	}


}
