/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A recording that is in progress
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class LiveRecording
{
	private String cause; // (optional) Cause for recording failure if failed
	private int    duration; // (optional) Duration in seconds of the recording
	private String format; // Recording format (wav, gsm, etc.)
	private String name; // Base name for the recording
	private int    silence_duration; // (optional) Duration of silence, in seconds, detected in the recording. This is only available if the recording was initiated with a non
	private String state; // State of recording
	private int    talking_duration; // (optional) Duration of talking, in seconds, detected in the recording. This is only available if the recording was initiated with a non
	private String target_uri; // URI for the channel or bridge being recorded


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public LiveRecording ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public LiveRecording (String _cause, int _duration, String _format, String _name, int _silence_duration, String _state, int _talking_duration, String _target_uri)
	{
		this.cause            = _cause;
		this.duration         = _duration;
		this.format           = _format;
		this.name             = _name;
		this.silence_duration = _silence_duration;
		this.state            = _state;
		this.talking_duration = _talking_duration;
		this.target_uri       = _target_uri;
	}
	/*
	 * Setters
	 */
	public void setCause (String _cause)
	{
		this.cause = _cause;
	}


	public void setDuration (int _duration)
	{
		this.duration = _duration;
	}


	public void setFormat (String _format)
	{
		this.format = _format;
	}


	public void setName (String _name)
	{
		this.name = _name;
	}


	public void setSilence_duration (int _silence_duration)
	{
		this.silence_duration = _silence_duration;
	}


	public void setState (String _state)
	{
		this.state = _state;
	}


	public void setTalking_duration (int _talking_duration)
	{
		this.talking_duration = _talking_duration;
	}


	public void setTarget_uri (String _target_uri)
	{
		this.target_uri = _target_uri;
	}


	/*
	 * Getters
	 */
	public String getCause ()
	{
		return this.cause;
	}


	public int getDuration ()
	{
		return this.duration;
	}


	public String getFormat ()
	{
		return this.format;
	}


	public String getName ()
	{
		return this.name;
	}


	public int getSilence_duration ()
	{
		return this.silence_duration;
	}


	public String getState ()
	{
		return this.state;
	}


	public int getTalking_duration ()
	{
		return this.talking_duration;
	}


	public String getTarget_uri ()
	{
		return this.target_uri;
	}


}
