/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Represents the state of a mailbox.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class Mailbox
{
	private String name; // Name of the mailbox.
	private int    new_messages; // Count of new messages in the mailbox.
	private int    old_messages; // Count of old messages in the mailbox.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Mailbox ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Mailbox (String _name, int _new_messages, int _old_messages)
	{
		this.name         = _name;
		this.new_messages = _new_messages;
		this.old_messages = _old_messages;
	}
	/*
	 * Setters
	 */
	public void setName (String _name)
	{
		this.name = _name;
	}


	public void setNew_messages (int _new_messages)
	{
		this.new_messages = _new_messages;
	}


	public void setOld_messages (int _old_messages)
	{
		this.old_messages = _old_messages;
	}


	/*
	 * Getters
	 */
	public String getName ()
	{
		return this.name;
	}


	public int getNew_messages ()
	{
		return this.new_messages;
	}


	public int getOld_messages ()
	{
		return this.old_messages;
	}


}
