/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Base type for errors and events
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class Message
{
	private String type; // Indicates the type of this message.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Message ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Message (String _type)
	{
		this.type = _type;
	}
	/*
	 * Setters
	 */
	public void setType (String _type)
	{
		this.type = _type;
	}


	/*
	 * Getters
	 */
	public String getType ()
	{
		return this.type;
	}


}
