/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Message object) Error event sent when required params are missing.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class MissingParams extends Message
{
	private List<String> params; // A list of the missing parameters


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public MissingParams ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public MissingParams (String _type, List<String> _params)
	{
		super (_type);
		this.params = _params;
	}
	/*
	 * Setters
	 */
	public void setParams (List<String> _params)
	{
		this.params = _params;
	}


	/*
	 * Getters
	 */
	public List<String> getParams ()
	{
		return this.params;
	}


}
