/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Event showing the completion of a recording operation.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.sql.Timestamp;

public class RecordingFinished extends Event
{
	private LiveRecording recording; // Recording control object


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public RecordingFinished ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public RecordingFinished (String _type, String _application, Timestamp _timestamp, LiveRecording _recording)
	{
		super (_type, _application, _timestamp);
		this.recording   = _recording;
	}
	/*
	 * Setters
	 */
	public void setRecording (LiveRecording _recording)
	{
		this.recording = _recording;
	}


	/*
	 * Getters
	 */
	public LiveRecording getRecording ()
	{
		return this.recording;
	}


}
