/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Effective user/group id
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class SetId
{
	private String group; // Effective group id.
	private String user; // Effective user id.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public SetId ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public SetId (String _group, String _user)
	{
		this.group = _group;
		this.user  = _user;
	}
	/*
	 * Setters
	 */
	public void setGroup (String _group)
	{
		this.group = _group;
	}


	public void setUser (String _user)
	{
		this.user = _user;
	}


	/*
	 * Getters
	 */
	public String getGroup ()
	{
		return this.group;
	}


	public String getUser ()
	{
		return this.user;
	}


}
