/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A media file that may be played back.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class Sound
{
	private List<FormatLangPair> formats; // The formats and languages in which this sound is available.
	private String               id; // Sound's identifier.
	private String               text; // (optional) Text description of the sound, usually the words spoken.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Sound ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Sound (List<FormatLangPair> _formats, String _id, String _text)
	{
		this.formats = _formats;
		this.id      = _id;
		this.text    = _text;
	}
	/*
	 * Setters
	 */
	public void setFormats (List<FormatLangPair> _formats)
	{
		this.formats = _formats;
	}


	public void setId (String _id)
	{
		this.id = _id;
	}


	public void setText (String _text)
	{
		this.text = _text;
	}


	/*
	 * Getters
	 */
	public List<FormatLangPair> getFormats ()
	{
		return this.formats;
	}


	public String getId ()
	{
		return this.id;
	}


	public String getText ()
	{
		return this.text;
	}


}
