/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Java code generated by apiGenerator.py
 * 10.17.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * The Sounds ARI API. See https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Sounds+REST+API for details.
 */

import com.sun.jersey.api.client.ClientResponse;
/*
 * Logging
*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SoundsARIAPI
{
	// Logging
	private static final Logger log = LoggerFactory.getLogger (SoundsARIAPI.class.getName ());
	/**
	 *
	 * list: List all sounds.
	 *
	 *
	 * Query parameters:
	 * @param lang: String: Lookup sound for a specific language.
	 * @param format: String: Lookup sound in a specific format.
	*/
	public static ClientResponse list (String query)
	{
		String RESTURLToUse = "/sounds";

		ClientResponse httpResponse = HTTPAPIForARI.get (RESTURLToUse, query);
		if (httpResponse.getStatus () == 200)
		{
			log.debug ("No errors caught in call to /sounds");
		}
		return httpResponse;
	}

	/**
	 *
	 * get: Get a sound's details.
	 *
	 *
	 * Path parameters:
	 * @param soundId: String: Sound's id
	*/
	public static ClientResponse get (String soundId)
	{
		String RESTURLToUse = "/sounds/{soundId}";

		// Correct URI using path params
		RESTURLToUse = RESTURLToUse.replace ("{soundId}", soundId);
		ClientResponse httpResponse = HTTPAPIForARI.get (RESTURLToUse);
		if (httpResponse.getStatus () == 200)
		{
			log.debug ("No errors caught in call to /sounds/{soundId}");
		}
		return httpResponse;
	}

}
