/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from Event object) Notification that a channel has entered a Stasis application.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;
import java.sql.Timestamp;

public class StasisStart extends Event
{
	private List<String> args; // Arguments to the application
	private Channel      channel; // Channel that entered the stasis application
	private Channel      replace_channel; // (optional)


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public StasisStart ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public StasisStart (String _type, String _application, Timestamp _timestamp, List<String> _args, Channel _channel, Channel _replace_channel)
	{
		super (_type, _application, _timestamp);
		this.args            = _args;
		this.channel         = _channel;
		this.replace_channel = _replace_channel;
	}
	/*
	 * Setters
	 */
	public void setArgs (List<String> _args)
	{
		this.args = _args;
	}


	public void setChannel (Channel _channel)
	{
		this.channel = _channel;
	}


	public void setReplace_channel (Channel _replace_channel)
	{
		this.replace_channel = _replace_channel;
	}


	/*
	 * Getters
	 */
	public List<String> getArgs ()
	{
		return this.args;
	}


	public Channel getChannel ()
	{
		return this.channel;
	}


	public Channel getReplace_channel ()
	{
		return this.replace_channel;
	}


}
