/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A key/value pair variable in a text message.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class TextMessageVariable
{
	private String key; // A unique key identifying the variable.
	private String value; // The value of the variable.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public TextMessageVariable ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public TextMessageVariable (String _key, String _value)
	{
		this.key   = _key;
		this.value = _value;
	}
	/*
	 * Setters
	 */
	public void setKey (String _key)
	{
		this.key = _key;
	}


	public void setValue (String _value)
	{
		this.value = _value;
	}


	/*
	 * Getters
	 */
	public String getKey ()
	{
		return this.key;
	}


	public String getValue ()
	{
		return this.value;
	}


}
