/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A text message.
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class TextMessage
{
	private String                    body; // The text of the message.
	private String                    from; // A technology specific URI specifying the source of the message. For sip and pjsip technologies, any SIP URI can be specified. For xmpp, the URI must correspond to the client connection being used to send the message.
	private String                    to; // A technology specific URI specifying the destination of the message. Valid technologies include sip, pjsip, and xmp. The destination of a message should be an endpoint.
	private List<TextMessageVariable> variables; // (optional) Technology specific key/value pairs associated with the message.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public TextMessage ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public TextMessage (String _body, String _from, String _to, List<TextMessageVariable> _variables)
	{
		this.body      = _body;
		this.from      = _from;
		this.to        = _to;
		this.variables = _variables;
	}
	/*
	 * Setters
	 */
	public void setBody (String _body)
	{
		this.body = _body;
	}


	public void setFrom (String _from)
	{
		this.from = _from;
	}


	public void setTo (String _to)
	{
		this.to = _to;
	}


	public void setVariables (List<TextMessageVariable> _variables)
	{
		this.variables = _variables;
	}


	/*
	 * Getters
	 */
	public String getBody ()
	{
		return this.body;
	}


	public String getFrom ()
	{
		return this.from;
	}


	public String getTo ()
	{
		return this.to;
	}


	public List<TextMessageVariable> getVariables ()
	{
		return this.variables;
	}


}
