/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 10.06.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * The value of a channel variable
 */
package com.hola.serverSide.ariApplication.ari;
/*
 * Import statements 
 */

public class Variable
{
	private String value; // The value of the variable requested


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Variable ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Variable (String _value)
	{
		this.value = _value;
	}
	/*
	 * Setters
	 */
	public void setValue (String _value)
	{
		this.value = _value;
	}


	/*
	 * Getters
	 */
	public String getValue ()
	{
		return this.value;
	}


}
