/*
 * Java code autogenerated by enumGenerator.py
 * 12.29.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * APPIEventType
 */
package com.hola.serverSide.appInterface.appi;

/*
 * Import statements 
 */
public enum APPIEventType
{
    AuthResponse               (1), // Authentication response message from the server to the app. Sent from server.
    InfoRequest                (2), // Information request message from the app.
    InfoResponse               (3), // Information request message from the app.
    StatusUpdate               (4), // Status update from the app. Includes current Skype, Google, VoIP, PSTN status etc. Sent from app.
    StatusUpdateResponse       (5), // Status update response from the server. Sent from server.
    ReachabilityRequest        (6), // Reachability request from the app. Typically pulled when the Hola! user opens the "contacts" screen on her app. Sent from app.
    ReachabilityResponse       (7), // Reachability response from the server. Sent from server.
    ReachabilityUpdate         (8), // Reachability update to the app from the server. Happens when the rechability has changed at some contact which will then be pushed to other users who are using this contact's information. Sent from server.
    ReachabilityUpdateResponse (9), // Reachability response from the app. Sent from app.
    GoingToBackground         (10), // The app is going to background.
    GoingToForeground         (11), // The app is going to foreground.
    AuthRequest               (20), // Authentication request message from the app. Pushed from app. No longer used.

    UNKNOWN                   (99);

    private final int eventTypeInt;


    APPIEventType (int _eventTypeInt)
    {
	this.eventTypeInt = _eventTypeInt;
    }

    public int getEventTypeInt ()
    {
	return this.eventTypeInt;
    }

    public String getTypeString ()
    {
	switch (this)
	    {
	    case InfoRequest:
		{
		    return "InfoRequest";
		}
	    case InfoResponse:
		{
		    return "InfoResponse";
		}
	    case AuthRequest:
		{
		    return "AuthRequest";
		}
	    case AuthResponse:
		{
		    return "AuthResponse";
		}
	    case StatusUpdate:
		{
		    return "StatusUpdate";
		}
	    case StatusUpdateResponse:
		{
		    return "StatusUpdateResponse";
		}
	    case ReachabilityRequest:
		{
		    return "ReachabilityRequest";
		}
	    case ReachabilityResponse:
		{
		    return "ReachabilityResponse";
		}
	    case ReachabilityUpdate:
		{
		    return "ReachabilityUpdate";
		}
	    case ReachabilityUpdateResponse:
		{
		    return "ReachabilityUpdateResponse";
		}
	    case GoingToBackground:
		{
		    return "GoingToBackground";
		}
	    case GoingToForeground:
		{
		    return "GoingToForeground";
		}
	    default:
		return "UNKNOWN APPIEventType TYPE";
	    }
    }
}
