/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from APPIEvent object) Contact add request sent from the app.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import com.fasterxml.jackson.annotation.JsonProperty;

public class ContactAddRequest extends APPIEvent
{
	private String usernameOrEmail; // The username (email) of the person whose contact is being requested.
	private String msgId; // The message ID for this message.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ContactAddRequest ()
	{
	   // For Jackson ObjectMapper's sanity!
		super ("ContactAddRequest");
	}
	public ContactAddRequest (String _usernameOrEmail, String _msgId)
	{
		super ("ContactAddRequest");
		this.usernameOrEmail = _usernameOrEmail;
		this.msgId           = _msgId;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("usernameOrEmail")
	public void setUsernameOrEmail (String _usernameOrEmail)
	{
		this.usernameOrEmail = _usernameOrEmail;
	}


	@JsonProperty ("msgId")
	public void setMsgId (String _msgId)
	{
		this.msgId = _msgId;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("usernameOrEmail")
	public String getUsernameOrEmail ()
	{
		return this.usernameOrEmail;
	}


	@JsonProperty ("msgId")
	public String getMsgId ()
	{
		return this.msgId;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "type: " + getType ()+ " " + "usernameOrEmail: " + usernameOrEmail+ " " + "msgId: " + msgId;
	}
}
