/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * A single Hola! contact.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Contact
{
	private String firstname; // The firstname of the contact.
	private String lastname; // The lastname of the contact.
	private String usernameOrEmail; // The username or email of this contact. This is the same usernameOrEmail that was used to locate this contact.
	private String extension; // The numeric extension that is currently being used also as an extension to make calls. (SIP handle is PJSIP/extension).

    private static final ObjectMapper objectMapper = new ObjectMapper ();
	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Contact ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Contact (String _firstname, String _lastname, String _usernameOrEmail, String _extension)
	{
		this.firstname       = _firstname;
		this.lastname        = _lastname;
		this.usernameOrEmail = _usernameOrEmail;
		this.extension       = _extension;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("firstname")
	public void setFirstname (String _firstname)
	{
		this.firstname = _firstname;
	}


	@JsonProperty ("lastname")
	public void setLastname (String _lastname)
	{
		this.lastname = _lastname;
	}


	@JsonProperty ("usernameOrEmail")
	public void setUsernameOrEmail (String _usernameOrEmail)
	{
		this.usernameOrEmail = _usernameOrEmail;
	}


	@JsonProperty ("extension")
	public void setExtension (String _extension)
	{
		this.extension = _extension;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("firstname")
	public String getFirstname ()
	{
		return this.firstname;
	}


	@JsonProperty ("lastname")
	public String getLastname ()
	{
		return this.lastname;
	}


	@JsonProperty ("usernameOrEmail")
	public String getUsernameOrEmail ()
	{
		return this.usernameOrEmail;
	}


	@JsonProperty ("extension")
	public String getExtension ()
	{
		return this.extension;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "firstname: " + firstname+ " " + "lastname: " + lastname+ " " + "usernameOrEmail: " + usernameOrEmail+ " " + "extension: " + extension;
	}
	/*
	 * get JSON string object
	 */
	public String toJsonString ()
	{
	    //ObjectMapper mapper = new ObjectMapper ();
		String thisBeanAsJson = null;
		try
		{
			thisBeanAsJson = objectMapper.writeValueAsString (this);
		}
		catch (JsonProcessingException e)
		{
			e.printStackTrace ();
		}
		finally
		{
			return thisBeanAsJson;
		}
	}
}
