/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from APPIEvent object) Contact add response sent from the server to the app.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import com.fasterxml.jackson.annotation.JsonProperty;

public class ContactAddResponse extends APPIEvent
{
	private String  msgId; // The message ID for this message.
	private boolean success; // The success indicator for this contact search.
	private String  remarks; // The remarks, if any. Populated if contact was not found, for example.
	private Contact contact; // The contact information.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ContactAddResponse ()
	{
	   // For Jackson ObjectMapper's sanity!
		super ("ContactAddResponse");
	}
	public ContactAddResponse (String _msgId, boolean _success, String _remarks, Contact _contact)
	{
		super ("ContactAddResponse");
		this.msgId   = _msgId;
		this.success = _success;
		this.remarks = _remarks;
		this.contact = _contact;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("msgId")
	public void setMsgId (String _msgId)
	{
		this.msgId = _msgId;
	}


	@JsonProperty ("success")
	public void setSuccess (boolean _success)
	{
		this.success = _success;
	}


	@JsonProperty ("remarks")
	public void setRemarks (String _remarks)
	{
		this.remarks = _remarks;
	}


	@JsonProperty ("contact")
	public void setContact (Contact _contact)
	{
		this.contact = _contact;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("msgId")
	public String getMsgId ()
	{
		return this.msgId;
	}


	@JsonProperty ("success")
	public boolean getSuccess ()
	{
		return this.success;
	}


	@JsonProperty ("remarks")
	public String getRemarks ()
	{
		return this.remarks;
	}


	@JsonProperty ("contact")
	public Contact getContact ()
	{
		return this.contact;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "type: " + getType ()+ " " + "msgId: " + msgId+ " " + "success: " + success+ " " + "remarks: " + remarks+ " " + "contact: " + contact;
	}
}
