/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from APPIEvent object) Sent for getting information regarding current calls ongoing.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import com.fasterxml.jackson.annotation.JsonProperty;

public class CurrentCallRequest extends APPIEvent
{


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public CurrentCallRequest ()
	{
	   // For Jackson ObjectMapper's sanity!
		super ("CurrentCallRequest");
	}
	/*
	 * Setters
	 */
	/*
	 * Getters
	 */
	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "type: " + getType ();
	}
}
