/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from APPIEvent object) Information request message from the app to the server.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import com.fasterxml.jackson.annotation.JsonProperty;

public class InfoRequest extends APPIEvent
{
	private String content; // Optional content. For future use.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public InfoRequest ()
	{
	   // For Jackson ObjectMapper's sanity!
		super ("InfoRequest");
	}
	public InfoRequest (String _content)
	{
		super ("InfoRequest");
		if (_content.equals (""))
		    {
			this.content = "NO_CONTENT";
		    }
		else
		    {
			this.content = _content;
		    }
	}
	/*
	 * Setters
	 */
	@JsonProperty ("content")
	public void setContent (String _content)
	{
		this.content = _content;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("content")
	public String getContent ()
	{
		return this.content;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "type: " + getType ()+ " " + "content: " + content;
	}
}
