/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from APPIEvent object) Reachability update to the app from the server. Happens when the rechability has changed at some contact which will then be pushed to other users who are using this contact's information. Sent from server.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import java.util.ArrayList;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

public class ReachabilityUpdate extends APPIEvent
{
	private boolean                  doNotDisturb; // The do not disturb status. True/False.
	private List<HandleReachability> reachabilities; // The list of this user's handle reachability information.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ReachabilityUpdate ()
	{
	   // For Jackson ObjectMapper's sanity!
		super ("ReachabilityUpdate");
	}
	public ReachabilityUpdate (boolean _doNotDisturb, List<HandleReachability> _reachabilities)
	{
		super ("ReachabilityUpdate");
		this.doNotDisturb   = _doNotDisturb;
		this.reachabilities = _reachabilities;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("doNotDisturb")
	public void setDoNotDisturb (boolean _doNotDisturb)
	{
		this.doNotDisturb = _doNotDisturb;
	}


	@JsonProperty ("reachabilities")
	public void setReachabilities (List<HandleReachability> _reachabilities)
	{
		this.reachabilities = _reachabilities;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("doNotDisturb")
	public boolean getDoNotDisturb ()
	{
		return this.doNotDisturb;
	}


	@JsonProperty ("reachabilities")
	public List<HandleReachability> getReachabilities ()
	{
		return this.reachabilities;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{

		String list0Str="[";
		for (HandleReachability var: reachabilities) 
		{
			list0Str += var.toString () + ", ";
		}
		list0Str += "]";
		return "type: " + getType ()+ " " + "doNotDisturb: " + doNotDisturb+ " " + "reachabilities: " + list0Str;
	}
}
