/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from APPIEvent object) Reachability response from the server. Sent from server.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import java.util.ArrayList;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

public class ReachabilityResponse extends APPIEvent
{
	private boolean                  doNotDisturb; // The do not disturb status. True/False.
	private String                   usernameOrEmail; // The username or email of the user whose reachability information is being sent from the server.
	private List<HandleReachability> reachabilities; // The list of this user's handle reachability information.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public ReachabilityResponse ()
	{
	   // For Jackson ObjectMapper's sanity!
		super ("ReachabilityResponse");
	}
	public ReachabilityResponse (boolean _doNotDisturb, String _usernameOrEmail, List<HandleReachability> _reachabilities)
	{
		super ("ReachabilityResponse");
		this.doNotDisturb    = _doNotDisturb;
		this.usernameOrEmail = _usernameOrEmail;
		this.reachabilities  = _reachabilities;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("doNotDisturb")
	public void setDoNotDisturb (boolean _doNotDisturb)
	{
		this.doNotDisturb = _doNotDisturb;
	}


	@JsonProperty ("usernameOrEmail")
	public void setUsernameOrEmail (String _usernameOrEmail)
	{
		this.usernameOrEmail = _usernameOrEmail;
	}


	@JsonProperty ("reachabilities")
	public void setReachabilities (List<HandleReachability> _reachabilities)
	{
		this.reachabilities = _reachabilities;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("doNotDisturb")
	public boolean getDoNotDisturb ()
	{
		return this.doNotDisturb;
	}


	@JsonProperty ("usernameOrEmail")
	public String getUsernameOrEmail ()
	{
		return this.usernameOrEmail;
	}


	@JsonProperty ("reachabilities")
	public List<HandleReachability> getReachabilities ()
	{
		return this.reachabilities;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{

		String list0Str="[";
		for (HandleReachability var: reachabilities) 
		{
			list0Str += var.toString () + ", ";
		}
		list0Str += "]";
		return "type: " + getType ()+ " " + "doNotDisturb: " + doNotDisturb+ " " + "usernameOrEmail: " + usernameOrEmail+ " " + "reachabilities: " + list0Str;
	}
}
