/*
 * Java code generated by beanGenerator.py
 * 02.12.2016
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * (Derived from APPIEvent object) Status update response from the server. Sent from server.
 */
package com.hola.serverSide.appInterface.appi;
/*
 * Import statements 
 */
import com.fasterxml.jackson.annotation.JsonProperty;

public class StatusUpdateResponse extends APPIEvent
{
	private String response; // (Optional) The response content back from the server.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public StatusUpdateResponse ()
	{
	   // For Jackson ObjectMapper's sanity!
		super ("StatusUpdateResponse");
	}
	public StatusUpdateResponse (String _response)
	{
		super ("StatusUpdateResponse");
		this.response = _response;
	}
	/*
	 * Setters
	 */
	@JsonProperty ("response")
	public void setResponse (String _response)
	{
		this.response = _response;
	}


	/*
	 * Getters
	 */
	@JsonProperty ("response")
	public String getResponse ()
	{
		return this.response;
	}


	/*
	 * Override of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "type: " + getType ()+ " " + "response: " + response;
	}
}
