/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/**
 * Java code autogenerated by beanGenerator.py
 * 11.19.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 *
 * The charging record object: captures the detail of each call transaction. Technically speaking,
 * a call can start with one caller, callee leg, and move to different caller and callee legs.
 * The legs may all have different cost profiles associated. This object captures the details of
 * the cost & rating for each leg of the call.
 *
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
package com.hola.serverSide.ariApplication.charging;
/*
 * Import statements 
 */

import java.time.LocalTime;

public class ChargingRecord
{
    private LegProfile  callerProfile; // The profile of the caller
    private LegProfile  calleeProfile; // The profile of the callee
    private LocalTime   start; // When the call started using these legs for the call.
    private LocalTime   end; // When the call ended using these legs for the call.
    private ServiceType serviceType; // The specific type of service (voice, video, SMS, Skype/Google call etc.).


    /*
     * Constructors
     * Empty/default (see 
     *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
     * full, and partial (for derived classes)
     *
     */
    public ChargingRecord ()
    {
	// For Jackson ObjectMapper's sanity!
    }
    public ChargingRecord (LegProfile _callerProfile, LegProfile _calleeProfile, LocalTime _start, LocalTime _end, ServiceType _serviceType)
    {
	this.callerProfile = _callerProfile;
	this.calleeProfile = _calleeProfile;
	this.start         = _start;
	this.end           = _end;
	this.serviceType   = _serviceType;
    }
    /*
     * Setters
     */
    public void setCallerProfile (LegProfile _callerProfile)
    {
	this.callerProfile = _callerProfile;
    }


    public void setCalleeProfile (LegProfile _calleeProfile)
    {
	this.calleeProfile = _calleeProfile;
    }


    public void setStart (LocalTime _start)
    {
	this.start = _start;
    }


    public void setEnd (LocalTime _end)
    {
	this.end = _end;
    }


    public void setServiceType (ServiceType _serviceType)
    {
	this.serviceType = _serviceType;
    }


    /*
     * Getters
     */
    public LegProfile getCallerProfile ()
    {
	return this.callerProfile;
    }


    public LegProfile getCalleeProfile ()
    {
	return this.calleeProfile;
    }


    public LocalTime getStart ()
    {
	return this.start;
    }


    public LocalTime getEnd ()
    {
	return this.end;
    }


    public ServiceType getServiceType ()
    {
	return this.serviceType;
    }


}
