/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 11.19.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * The profile of a leg used in a call.
 */
package com.hola.serverSide.ariApplication.charging;
/*
 * Import statements 
 */

public class LegProfile
{
    private String handle; // The handle that was used. PSTN number, Skype ID, etc.
    private Rating rating; // The rating that was used.
    private Cost   cost; // The cost of this leg.

    /*
     * Constructors
     * Empty/default (see 
     *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
     * full, and partial (for derived classes)
     *
     */
    public LegProfile ()
    {
	// For Jackson ObjectMapper's sanity!
    }
    public LegProfile (String _handle, Rating _rating, Cost _cost)
    {
	this.handle = _handle;
	this.rating = _rating;
	this.cost   = _cost;
    }
    /*
     * Setters
     */
    public void setHandle (String _handle)
    {
	this.handle = _handle;
    }


    public void setRating (Rating _rating)
    {
	this.rating = _rating;
    }


    public void setCost (Cost _cost)
    {
	this.cost = _cost;
    }


    /*
     * Getters
     */
    public String getHandle ()
    {
	return this.handle;
    }


    public Rating getRating ()
    {
	return this.rating;
    }


    public Cost getCost ()
    {
	return this.cost;
    }
}
