/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/**
 * Java code autogenerated by beanGenerator.py
 * 11.19.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc. *
 *
 * The rating of a leg used in a call.
 */
package com.hola.serverSide.ariApplication.charging;
/*
 * Import statements 
 */

public class Rating
{
    private double charge; // The charge/rating.
    private String ratingCurrency; // The rating currency.
    private int    ratingGranularity; // The rating time duration

    /*
     * Constructors
     * Empty/default (see 
     *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
     * full, and partial (for derived classes)
     *
     */
    public Rating ()
    {
	// For Jackson ObjectMapper's sanity!
    }
    public Rating (double _charge, String _ratingCurrency, int _ratingGranularity)
    {
	this.charge            = _charge;
	this.ratingCurrency    = _ratingCurrency;
	this.ratingGranularity = _ratingGranularity;
    }
    /*
     * Setters
     */
    public void setCharge (double _charge)
    {
	this.charge = _charge;
    }


    public void setRatingCurrency (String _ratingCurrency)
    {
	this.ratingCurrency = _ratingCurrency;
    }


    public void setRatingGranularity (int _ratingGranularity)
    {
	this.ratingGranularity = _ratingGranularity;
    }


    /*
     * Getters
     */
    public double getCharge ()
    {
	return this.charge;
    }


    public String getRatingCurrency ()
    {
	return this.ratingCurrency;
    }


    public int getRatingGranularity ()
    {
	return this.ratingGranularity;
    }
}
