/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by enumGenerator.py
 * 12.20.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * ResultCode
 */
package com.hola.serverSide.ariApplication.common;

/*
 * Import statements 
 */
public enum ResultCode
{
	Success (1), // The generic return value of successful execution.
	Error   (2), // The generic return value of erroneous execution.


	UNKNOWN (99); // Unknown result code.


	private final int resultTypeInt;


	ResultCode (int _resultTypeInt)
	{
		this.resultTypeInt = _resultTypeInt;
	}

	public int getResultTypeInt ()
	{
		return this.resultTypeInt;
	}

	public String getTypeString ()
	{
		switch (this)
		{
			case Success:
			{
				return "Success";
			}
			case Error:
			{
				return "Error";
			}
			case UNKNOWN:
			{
				return "UNKNOWN";
			}
			default:
				 return "UNKNOWN ResultCode TYPE";
		}
	}
}
