/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 11.16.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Hola call context
 */
package com.hola.serverSide.ariApplication.call;
/*
 * Import statements 
 */
import java.time.LocalTime;

public class CallContext
{
    private LocalTime currentTime; // Current time.
    private String    caller; // Caller.
    private String    callee; // Callee.
    private Location  callerLocation; // Caller's rich location context.
    private Location  calleeLocation; // Callee's rich location context.
    private String    logMessage; // Debug message sent to log action

    /*
     * Constructors
     * Empty/default (see 
     *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
     * full, and partial (for derived classes)
     *
     */
    public CallContext ()
    {
	// For Jackson ObjectMapper's sanity!
    }
    public CallContext (String _caller, String _callee, Location _callerLocation, Location _calleeLocation)
    {
	this.currentTime    = LocalTime.now ();
	this.caller         = _caller;
	this.callee         = _callee;
	this.callerLocation = _callerLocation;
	this.calleeLocation = _calleeLocation;
	this.logMessage   = "<>";
    }
    /*
     * Setters
     */
    public void setCurrentTime (LocalTime _currentTime)
    {
	this.currentTime = _currentTime;
    }


    public void setCaller (String _caller)
    {
	this.caller = _caller;
    }


    public void setCallee (String _callee)
    {
	this.callee = _callee;
    }


    public void setCallerLocation (Location _callerLocation)
    {
	this.callerLocation = _callerLocation;
    }


    public void setCalleeLocation (Location _calleeLocation)
    {
	this.calleeLocation = _calleeLocation;
    }

    public void setDebugMessage (String _logMessage)
    {
	this.logMessage = _logMessage;
    }

    /*
     * Getters
     */
    public LocalTime getCurrentTime ()
    {
	return this.currentTime;
    }


    public String getCaller ()
    {
	return this.caller;
    }


    public String getCallee ()
    {
	return this.callee;
    }


    public Location getCallerLocation ()
    {
	return this.callerLocation;
    }


    public Location getCalleeLocation ()
    {
	return this.calleeLocation;
    }


    public String getLogMessage ()
    {
	return this.logMessage;
    }
}
