/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 12.18.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Device for the caller or callee legs.
 */
package com.hola.serverSide.ariApplication.call;
/*
 * Import statements 
 */

public class Device
{
	private String name; // The device name.
	private String type; // The device type.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Device ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Device (String _name, String _type)
	{
		this.name = _name;
		this.type = _type;
	}
	/*
	 * Setters
	 */
	public void setName (String _name)
	{
		this.name = _name;
	}


	public void setType (String _type)
	{
		this.type = _type;
	}


	/*
	 * Getters
	 */
	public String getName ()
	{
		return this.name;
	}


	public String getType ()
	{
		return this.type;
	}


	/*
	 * Overide of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
		return "name: " + name+ " " + "type: " + type;
	}
}
