/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 12.18.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Leg information for caller or callee.
 */
package com.hola.serverSide.ariApplication.call;
/*
 * Import statements 
 */

import com.hola.serverSide.ariApplication.db.beans.HolaAccount;
public class LegInfo
{
	private HolaAccount holaAccount; // The holaAccount involved in the call. "Null" object for external callers.
	private Device device; // The device the leg is using.
	private String handle; // The handle the holaAccount is using to be in the call. Not null.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public LegInfo ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public LegInfo (HolaAccount _holaAccount, Device _device, String _handle)
	{
		this.holaAccount = _holaAccount;
		this.device = _device;
		this.handle = _handle;
	}
	/*
	 * Setters
	 */
	public void setHolaAccount (HolaAccount _holaAccount)
	{
		this.holaAccount = _holaAccount;
	}


	public void setDevice (Device _device)
	{
		this.device = _device;
	}


	public void setHandle (String _handle)
	{
		this.handle = _handle;
	}


	/*
	 * Getters
	 */
	public HolaAccount getHolaAccount ()
	{
		return this.holaAccount;
	}


	public Device getDevice ()
	{
		return this.device;
	}


	public String getHandle ()
	{
		return this.handle;
	}


	/*
	 * Overide of toString() to help debug, log etc.
	 */
	@Override
	public String toString ()
	{
	    return "holaAccount: " + holaAccount.toString ()+ " " + "device: " + device+ " " + "handle: " + handle;
	}
}
