/*
 * This source code file is the property of Pacifi, Inc.
 * Copyright: 2015-2016.
 * All rights reserved.  
 * 
 * @author: Sonny Rajagopalan
 * @copyright: Pacifi, Inc.
 */
/*
 * Java code autogenerated by beanGenerator.py
 * 11.16.2015
 * Sonny Rajagopalan/Pacifi, Inc.
 * Copyright, Pacifi, Inc.
 *
 * Rich location context for a call
 */
package com.hola.serverSide.ariApplication.call;
/*
 * Import statements 
 */
import java.util.ArrayList;
import java.util.List;

public class Location
{
	private String       connectedSSID; // SSID of the WiFi access point user is connected to.
	private List<String> listOfSSIDsSeen; // List of other SSIDs that are seen around the user.
	private String       threeGPP_MCC; // Mobile Country Code of threeGPP network user is connected to.
	private String       threeGPP_MNC; // Mobile Network Code of threeGPP network user is connected to.


	/*
	 * Constructors
	 * Empty/default (see 
	 *   http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class
	 * full, and partial (for derived classes)
	 *
	 */
	public Location ()
	{
	   // For Jackson ObjectMapper's sanity!
	}
	public Location (String _connectedSSID, List<String> _listOfSSIDsSeen, String _threeGPP_MCC, String _threeGPP_MNC)
	{
		this.connectedSSID   = _connectedSSID;
		this.listOfSSIDsSeen = _listOfSSIDsSeen;
		this.threeGPP_MCC        = _threeGPP_MCC;
		this.threeGPP_MNC        = _threeGPP_MNC;
	}
	/*
	 * Setters
	 */
	public void setConnectedSSID (String _connectedSSID)
	{
		this.connectedSSID = _connectedSSID;
	}


	public void setListOfSSIDsSeen (List<String> _listOfSSIDsSeen)
	{
		this.listOfSSIDsSeen = _listOfSSIDsSeen;
	}


	public void setthreeGPP_MCC (String _threeGPP_MCC)
	{
		this.threeGPP_MCC = _threeGPP_MCC;
	}


	public void setthreeGPP_MNC (String _threeGPP_MNC)
	{
		this.threeGPP_MNC = _threeGPP_MNC;
	}


	/*
	 * Getters
	 */
	public String getConnectedSSID ()
	{
		return this.connectedSSID;
	}


	public List<String> getListOfSSIDsSeen ()
	{
		return this.listOfSSIDsSeen;
	}


	public String getthreeGPP_MCC ()
	{
		return this.threeGPP_MCC;
	}


	public String getthreeGPP_MNC ()
	{
		return this.threeGPP_MNC;
	}


}
